services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - dev

  django:
    build:
      context: ./project
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    networks:
      - dev
    volumes:
      - postgres_data

      

  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - django
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    environment:
      - SERVER_NAME=127.0.0.1
    networks:
      - dev

volumes:
  postgres_data:

networks:
  dev: